version: 2
jobs:
  build:
    # working_directory can not use relative path. Workaround is use absolute path. https://circleci.com/docs/2.0/local-jobs/#relative-path-for-working_directory
    working_directory: ~/WebStruct
    docker:
      - image: swift:4.0
    steps:
      - checkout
      - run:
          name: Run build tests
          command: |
            swift package clean
            swift build
            swift build -c release
            swift test
